services:
# WORDPRESS + PHP
  wordpress:
    image: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

  nginx:
# NGINX
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

  mariadb:
# MARIADB
    image: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
# ADMINER
    image: adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lle-cout/data/mariadb

  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lle-cout/data/wordpress

networks:
  inception:
    driver: bridge
