# ---- CONTAINERS ---- #

services:
# WORDPRESS + PHP
  wordpress:
    image: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

# NGINX
  nginx:
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

# MARIADB
  mariadb:
    image: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

# ADMINER + PHP
  adminer:
    image: adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    restart: unless-stopped

# PORTAINER
  portainer:
    image: portainer
    build: requirements/bonus/portainer
    networks:
      - inception
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# ---- VOLUMES ---- #

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lle-cout/data/mariadb

  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lle-cout/data/wordpress

  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lle-cout/data/portainer

# ---- NETWORKS ---- #

networks:
  inception:
    driver: bridge
